#!/usr/bin/env python2
'''
Code for handling the reading of data from the PTI Fluorescence Spectrometer.
It is assumed that the data is the text file generated by 'Export Session'.
Some of this code borrows from David's github repository: https://github.com/davidjaffe/QY
'''

import sys
import os
import numpy as np
from ROOT import TH1D, TFile, gROOT, TCanvas, TGraph, TLegend, TGraphErrors, gStyle

class FluorSpecReader():
    '''
    Read and process data from the PTI Flourescence Spectrometer.
    
    It is assumed that the data is a text file generated either by 'Export Session',
    or 'Export Trace'.
    '''
    def __init__(self):
        #Initialize parameters

